### ISSUE TITLE
Implement  framework to reasize site

### ISSUE THREAD

**Issue by Gerardogg** [OpenPymeMx/Point-of-Sale-Enhanced#22]
Implement  framework to implement  css for a good display, the proposal are:

-Lessframework
-Gumby
-Foundation

**Comment by Gerardogg** [comment]
Time to  review Wednesday 17

**Comment by Gerardogg** [comment]
Time to choose  a framework Sunday 14

**Comment by agb80** [comment]
Framework chosen inuit.css. Moving the issue to openrestaurant-web project

**Comment by Gerardogg** [comment]
This need revicion and more improve

**Comment by agb80** [comment]
But the framework is not being implemented here, instead this must be an issue on the web project.

Here is added on the web project: https://github.com/Fedrojesa/openrestaurant_web/issues/1
