### ISSUE TITLE
improve tickets 

### ISSUE THREAD

**Issue by Gerardogg** [OpenPymeMx/Point-of-Sale-Enhanced#23]
Make changes to look in right form print tickets

**Comment by agb80** [comment]
The solution we are going to go for improve how the tickets are printed & generated and also for make them easy to customize is using the Aeroo reports module.

Technically the approach is going to be the follow discussed on: http://help.openerp.com/question/475/how-to-setup-pos-printer-and-scanner-in-openerp-61/ so I'm going to close this issue and create two new ones:

1.- Make PoS generate ticket using Aeroo reports
2.- Make PoS print directly from javascript using cups
