### ISSUE TITLE
I got this error when i'm trying to install pos_restaurant

### ISSUE THREAD

**Issue by aravinthu** [OpenPymeMx/Point-of-Sale-Enhanced#32]
No such external ID currently defined in the system: pos_restaurant.group_pos_manager

**Comment by agb80** [comment]
Sorry for not being able to answer before you close the issue, would you mind share what was the cause and how do you solve it?

**Comment by aravinthu** [comment]
Thanks For Your Response

That was just demo data problem so i created DB without demo data that pblm
was solved..

But i got this Error (Refer attachment) -- POS session did not load After i
installed pos_cashier & pos_restaurant.. (Point-of-Sale-Enhanced)

On Tue, May 27, 2014 at 2:13 AM, agb80 notifications@github.com wrote:

> Sorry for not being able to answer before you close the issue, would you
> mind share what was the cause and how do you solve it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Fedrojesa/Point-of-Sale-Enhanced/issues/32#issuecomment-44216949
> .

## 

Regards

Aravinth D
(+91 - 999 40 40 518)

**Comment by agb80** [comment]
Good to know, thanks
