### ISSUE TITLE
how to use numeric keypad in pos??

### ISSUE THREAD

**Issue by hydrosIII** [OpenPymeMx/Point-of-Sale-Enhanced#33]
Hi im trying these pos as i need a pos that is keyboard friendly, instead of touchpad friendly.
I have read the code and i see that implements a blockage of the pos and then it  begins to accept keystrokes from the numpad. There is something in the code about connect/disconnect. I have tried this pos and also the enhanced point of sale, that implement the same feature, and after clicking it like crazy for hours, and using different combinations of keys it doesnt seems to work. 

Any idea of how to make it work??

**Comment by agb80** [comment]
Please use development branch for that, there are several bug fixing done on that branch. Also other shortcuts have been implemented:

1.- Ctrl+F -> Focus on product search box
2.- Hit Enter when there is only one product on search box automatically add product to receipt
3.- Function keys (F1, F2, etc) are mapping to payment methods
4.- Hit Enter on payment method automatically validates the receipt

Let me know if you have any problem to fix it.

**Comment by hydrosIII** [comment]
Hi, im using developing branch at it works !!! . It is really fast for
sales just if you add this few keys. Thank you.
Are there other keymappings besides the ones you write about them up? Any
way to use the numpad ?? i mean for exmaple to enter 10 products. I have
been checking this module: http://forum.openerp.com/forum/topic35937.html .
And i think it has similar code that the one you made, but even if i
followed the instructions the numpad is not working at all. Any ideas??

Thank you very much for the great support

2014-06-05 20:49 GMT-05:00 agb80 notifications@github.com:

> Please use development branch for that, there are several bug fixing done
> on that branch. Also other shortcuts have been implemented:
> 
> 1.- Ctrl+F -> Focus on product search box
> 2.- Hit Enter when there is only one product on search box automatically
> add product to receipt
> 3.- Function keys (F1, F2, etc) are mapping to payment methods
> 4.- Hit Enter on payment method automatically validates the receipt
> 
> Let me know if you have any problem to fix it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fedrojesa/Point-of-Sale-Enhanced/issues/33#issuecomment-45295383
> .

## 

_Por favor, evite enviarme documentos adjuntos en formato Word Excel o
PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
ods, además de documentos en formato pdfSi realmente es necesario enviarme
un documento en formato Word, por favor utilize el formato .doc en lugar de
.docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
http://es.libreoffice.org/http://getgnulinux.org/es
http://getgnulinux.org/es_

**Comment by agb80** [comment]
Yea, we took the idea from that post, so the system will work with numpad as pointed there.  

If it's not working, please ensure that  _Num lock_ is on, as different key code is send to javascript depending on Num lock status.

Also ensure that you are putting your custom codes on _Reference_ field on the product form, not working with EAN or barcodes.

**Comment by hydrosIII** [comment]
My codes are sotroed on reference field, but i have tried with different
numpad combinations and it is not working. Any specific instrucitons??

Are these supposed to be the keybindings??:

'/' - X Quantity
'*' - AMT Manual Price Override
'-' - % - Discount %
'+' - PLU (Product Code)
Keyboard "Back Space" and "Delete" keys may be used to clear the buffer.
Examples:
1. Add a product
(code: 100, quantity: 1, Price:list price, no discount)
Cash Register: 100 [PLU]
Numeric Keypad: 100 +

Example :

Add 9 pieces of a product
(code: 102, quantity: 9, Price: list price, no discount)
Cash Register: 9 [ X ] 102 [PLU]
Numeric Keypad: 9 / 102 +

I have re-read this like 100 times and tried  another 100. I just dont
understand it is suppossed to be easy.

My questions?? do you have to be in the search field to use these
keybindngs??
or do you have to be out of the search field??

Any particular browser you recommend?? What window manager/DE are you
using? it may be an issue of the particular WM grabbing the keys.

Thanks

2014-06-06 14:43 GMT-05:00 agb80 notifications@github.com:

> Yea, we took the idea from that post, so the system will work with numpad
> as pointed there.
> 
> If it's not working, please ensure that _Num lock_ is on, as different
> key code is send to javascript depending on Num lock status.
> 
> Also ensure that you are putting your custom codes on _Reference_ field
> on the product form, not working with EAN or barcodes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fedrojesa/Point-of-Sale-Enhanced/issues/33#issuecomment-45376632
> .

## 

_Por favor, evite enviarme documentos adjuntos en formato Word Excel o
PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
ods, además de documentos en formato pdfSi realmente es necesario enviarme
un documento en formato Word, por favor utilize el formato .doc en lugar de
.docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
http://es.libreoffice.org/http://getgnulinux.org/es
http://getgnulinux.org/es_

**Comment by hydrosIII** [comment]
Are you using the numpad that is integrated with keyboard, or do you
recommend to use an especial numpad device, like a usb numpad??

2014-06-07 15:29 GMT-05:00 Marco Galicia galprasmarco@gmail.com:

> My codes are sotroed on reference field, but i have tried with different
> numpad combinations and it is not working. Any specific instrucitons??
> 
> Are these supposed to be the keybindings??:
> 
> '/' - X Quantity
> '*' - AMT Manual Price Override
> '-' - % - Discount %
> '+' - PLU (Product Code)
> Keyboard "Back Space" and "Delete" keys may be used to clear the buffer.
> Examples:
> 1. Add a product
> (code: 100, quantity: 1, Price:list price, no discount)
> Cash Register: 100 [PLU]
> Numeric Keypad: 100 +
> 
> Example :
> 
> Add 9 pieces of a product
> (code: 102, quantity: 9, Price: list price, no discount)
> Cash Register: 9 [ X ] 102 [PLU]
> Numeric Keypad: 9 / 102 +
> 
> I have re-read this like 100 times and tried  another 100. I just dont
> understand it is suppossed to be easy.
> 
> My questions?? do you have to be in the search field to use these
> keybindngs??
> or do you have to be out of the search field??
> 
> Any particular browser you recommend?? What window manager/DE are you
> using? it may be an issue of the particular WM grabbing the keys.
> 
> Thanks
> 
> 2014-06-06 14:43 GMT-05:00 agb80 notifications@github.com:
> 
> Yea, we took the idea from that post, so the system will work with numpad
> 
> > as pointed there.
> > 
> > If it's not working, please ensure that _Num lock_ is on, as different
> > key code is send to javascript depending on Num lock status.
> > 
> > Also ensure that you are putting your custom codes on _Reference_ field
> > on the product form, not working with EAN or barcodes.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Fedrojesa/Point-of-Sale-Enhanced/issues/33#issuecomment-45376632
> > .
> 
> ## 
> 
> _Por favor, evite enviarme documentos adjuntos en formato Word Excel o
> PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
> ods, además de documentos en formato pdfSi realmente es necesario enviarme
> un documento en formato Word, por favor utilize el formato .doc en lugar de
> .docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
> http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
> http://es.libreoffice.org/ http://getgnulinux.org/es
> http://getgnulinux.org/es_

## 

_Por favor, evite enviarme documentos adjuntos en formato Word Excel o
PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
ods, además de documentos en formato pdfSi realmente es necesario enviarme
un documento en formato Word, por favor utilize el formato .doc en lugar de
.docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
http://es.libreoffice.org/http://getgnulinux.org/es
http://getgnulinux.org/es_

**Comment by agb80** [comment]
My answers in line to be easier to read

On 07/06/14 15:29, hydrosII wrote:

> My codes are sotroed on reference field, but i have tried with different
> numpad combinations and it is not working. Any specific instrucitons??
> 
> Are these supposed to be the keybindings??:
> 
> '/' - X Quantity
> '*' - AMT Manual Price Override
> '-' - % - Discount %
> '+' - PLU (Product Code)
> Keyboard "Back Space" and "Delete" keys may be used to clear the buffer.
> Examples:
> 1. Add a product
> (code: 100, quantity: 1, Price:list price, no discount)
> Cash Register: 100 [PLU]
> Numeric Keypad: 100 +
> 
> Example :
> 
> Add 9 pieces of a product
> (code: 102, quantity: 9, Price: list price, no discount)
> Cash Register: 9 [ X ] 102 [PLU]
> Numeric Keypad: 9 / 102 +

That are exactly the implemented keybinds

> I have re-read this like 100 times and tried another 100. I just dont
> understand it is suppossed to be easy.
> 
> My questions?? do you have to be in the search field to use these
> keybindngs??
> or do you have to be out of the search field??
> You need to be out of the search field, just create a new order and you 
> are ready to start using the keybinds. If you are on search field any 
> type is going to be considered as raw chars to search on products list.
> 
> Any particular browser you recommend?? What window manager/DE are you
> using? it may be an issue of the particular WM grabbing the keys.
> 
> We have tested on firefox and chrome on unix and windows environments. 
> Maybe look for any errors on your browser javascript console.

We recommend to use point of sale on an new user profile an full screen. 
This is working fine with chromium and ubuntu/mint stations.

We are using with full keyboards, don't have try using just numpad 
devices but will be work as well.
